generator: admingenerator.generator.doctrine
params:
  model: Mba\PageBundle\Entity\Page
  namespace_prefix: Mba
  bundle_name: PageBundle
  fields: ~

builders:
  list:
    params:
      title: Pages
      display: [title, background, active, include_in_menu, created]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: []
  new:
    params:
      title: Create a new Page
      display: 
        Content: [title, background, content]
        Settings: [active, include_in_menu]
        Meta Tags: [meta_title, meta_description, meta_keywords]
      actions:
        list: ~
  edit:
    params:
      title: Edit Page - {{ Page.title}}
      display: 
        Content: [title, background, content]
        Settings: [active, include_in_menu]
        Meta Tags: [meta_title, meta_description, meta_keywords]
      actions:
        list: ~
  delete: ~
