imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true      

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        compass: ~
        sass: ~        
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar
    bundles: ["OryzoneBoilerplateBundle"]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        #mappings:
        #    StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false    

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Mba\UserBundle\Entity\User
    
stof_doctrine_extensions: 
    orm: 
        default: 
            sluggable: true
            timestampable: true
            
knp_menu:
    twig: true            
    
admingenerator_generator:
    base_admin_template: AdmingeneratorGeneratorBundle::base_admin_assetic_less.html.twig
    use_propel: false
    use_doctrine_orm: true
    use_doctrine_odm: false
    overwrite_if_exists: true    

gregwar_captcha: ~    

trsteel_ckeditor:
    class: Trsteel\CkeditorBundle\Form\CkeditorType
    toolbar: ['document', 'clipboard', 'editing', '/', 'basicstyles', 'paragraph', 'links', '/', 'insert', 'styles', 'tools']
    toolbar_groups:
        document: ['Source','-','Save','-','Templates']
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: ['Find','Replace','-','SelectAll']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']
        links: ['Link','Unlink','Anchor']
        insert: ['Image','Flash','Table','HorizontalRule']
        styles: ['Styles','Format']
        tools: ['Maximize', 'ShowBlocks']
    ui_colour: '#000000'
    startup_outline_blocks: true
    width: 800 #Integer or %
    height: 300 #Integer or %       
    
avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: media/cache
    driver:       gd
    filters:  
        promo_thumb:
            type:    thumbnail
            options: { size: [210, 110], mode: outbound }                
        
vich_uploader:
    db_driver: orm # or mongodb
    web_dir_name: web
    twig: true
    mappings:
        promoImage:
            upload_dir: %kernel.root_dir%/../web/uploads/images/promo                  
            namer: ~ # specify a namer service id for this entity, null default
            delete_on_remove: false # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load
        videoFile:
            upload_dir: %kernel.root_dir%/../web/uploads/videos
            namer: ~ # specify a namer service id for this entity, null default
            delete_on_remove: false # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load 
        imageFile:
            upload_dir: %kernel.root_dir%/../web/uploads/images/backgrounds
            namer: ~ # specify a namer service id for this entity, null default
            delete_on_remove: false # determines whether to delete file upon removal of entity
            inject_on_load: true # determines whether to inject a File instance upon load             
            
          
                