MbaBlogBundle_admin:
    resource: "@MbaBlogBundle/Controller/Blog/"
    type:     admingenerator
    prefix:   /admin/blog

MbaBlogBundle:
    resource: "@MbaBlogBundle/Controller/"
    type:     annotation
    prefix:   /

_imagine:
    resource: .
    type:     imagine   
    
MbaCautiousAdminBundle_admin_mba_cautious_admin_bundle_short_film:
    resource: "@MbaCautiousAdminBundle/Controller/ShortFilm/"
    type:     admingenerator
    prefix:   /admin/short-film
    
MbaCautiousAdminBundle_admin_mba_cautious_admin_bundle_promo:
    resource: "@MbaCautiousAdminBundle/Controller/Promo/"
    type:     admingenerator
    prefix:   /admin/promo
    
MbaCautiousAdminBundle_admin_mba_cautious_admin_bundle_podcast:
    resource: "@MbaCautiousAdminBundle/Controller/Podcast/"
    type:     admingenerator
    prefix:   /admin/podcast

MbaCautiousBundle:
    resource: "@MbaCautiousBundle/Controller/"
    type:     annotation
    prefix:   /
    
MbaPageBundle_admin_mba_page_bundle_page:
    resource: "@MbaPageBundle/Controller/Page/"
    type:     admingenerator
    prefix:   /admin/pages
    
MbaGlobalSettingsBundle_admin_mba_global_settings_bundle_gs:
    resource: "@MbaGlobalSettingsBundle/Controller/Gs/"
    type:     admingenerator
    prefix:   /admin/global_settings
   
MbaPageBundle_admin_mba_page_bundle_page:
    resource: "@MbaPageBundle/Controller/Page/"
    type:     admingenerator
    prefix:   /admin/pages
    
MbaDashboardBundle:
    resource: "@MbaDashboardBundle/Controller/"
    type:     annotation
    prefix:   /    
    
#user related routes    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

cms_page:
    pattern: /{slug}/
    defaults: { _controller: MbaCautiousBundle:Page:index }
    requirements:
      slug: "[A-Za-z0-9\-]+"

# Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal
