generator: admingenerator.generator.doctrine
params:
  model: Mba\CautiousBundle\Entity\Background
  namespace_prefix: Mba
  bundle_name: CautiousAdminBundle
  fields: ~

builders:
  list:
    params:
      title: Backgrounds
      display: [title, image_name, poster_image_name, video_mp4_name, created]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: []
  new:
    params:
      title: Create new Backgound
      display: 
        content: [title]
      actions:
        list: ~
  edit:
    params:
      title: Edit Background - "{{ Background.title }}"
      display:
        content: [title]
      actions:
        list: ~
  delete: ~
