generator: admingenerator.generator.doctrine
params:
  model: Mba\CautiousBundle\Entity\Podcast
  namespace_prefix: Mba
  bundle_name: CautiousAdminBundle
  fields: ~

builders:
  list:
    params:
      title: Podcasts
      display: [title, subtitle, podcast_date, active]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: []
  new:
    params:
      title: New Podcast
      display: 
        Content: [title, subtitle]        
        Settings: [podcast_date, active]
      actions:
        list: ~
  edit:
    params:
      title: Edit Podcast - "{{ Podcast.title }}"
      display: 
        Content: [title, subtitle]
        Settings: [podcast_date, active]      
      actions:
        list: ~
  delete: ~
