generator: admingenerator.generator.doctrine
params:
  model: Mba\CautiousBundle\Entity\Promo
  namespace_prefix: Mba
  bundle_name: CautiousAdminBundle
  fields: ~

builders:
  list:
    params:
      title: Promos
      display: [title, director, client, promo_date, active]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: []
  new:
    params:
      title: New Promo 
      display: 
        Content: [title, director, client, description]
        Media: [video_url]
        Settings: [active, promo_date]
      actions:
        list: ~
  edit:
    params:
      title: Edit Promo - "{{ Promo.title }}"
      display: 
        Content: [title, director, client, description]
        Media: [video_url]
        Settings: [active, promo_date]
      actions:
        list: ~
  delete: ~
