generator: admingenerator.generator.doctrine
params:
  model: Mba\CautiousBundle\Entity\ShortFilm
  namespace_prefix: Mba
  bundle_name: CautiousAdminBundle
  fields: ~

builders:
  list:
    params:
      title: Short Film
      display: [title, director, client, short_film_date, active]      
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: []
  new:
    params:
      title: New Short Film
      display: 
        Content: [title, director, client, description]
        Media: [video_url]
        Settings: [active, short_film_date]      
      actions:
        list: ~
  edit:
    params:      
      title: Edit Short Film Entry - "{{ ShortFilm.title }}"
      display: 
        Content: [title, director, client, description]
        Media: [video_url]
        Settings: [active, short_film_date]      
      actions:
        list: ~
  delete: ~
